apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - patch: |-
      - op: add
        path: /imagePullSecrets
        value:
          - name: ecr-secret
    target:
      kind: ServiceAccount
      name: app-service-account
  - path: application-argocd-minikube.yaml
