apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  labels:
    app: python-basic-web
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-basic-web
      version: blue
  template:
    metadata:
      labels:
        app: python-basic-web
        version: blue
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: python-basic-web
          image: 156041411098.dkr.ecr.eu-west-3.amazonaws.com/python_web_app:blue
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http-port
          volumeMounts:
            - name: health
              mountPath: /health.html
              subPath: health.html

          startupProbe:
            httpGet:
              port: 5000
              path: /health.html
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 12

          livenessProbe:
            httpGet:
              port: 5000
              path: /health.html
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              port: 5000
              path: /health.html
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: health
          configMap:
            name: nginx-health
            defaultMode: 0444
