apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-health-config.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
  - service-blue.yaml
  - service-green.yaml
  - service-account.yaml
  - application-argocd.yaml
