apiVersion: v1
kind: Service
metadata:
  name: app-blue-service
spec:
  type: ClusterIP
  selector:
    app: python-basic-web
    version: blue
  ports:
    - port: 80
      targetPort: http-port
      protocol: TCP
      name: http
