apiVersion: v1
kind: Secret
metadata:
  name: mi-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/SergioCMDev/Infra-AWS-EKS-Python
  # username: mi-usuario
  # password: mi-token # o un GitHub PAT
